name: Documentation
description: Suggest an improvement to the documentation.
title: "[DOCS]: "
labels: ["documentation"]
assignees:
  - 3dcoded
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation issue!
  - type: checkboxes
    id: what-type
    attributes:
      label: What kind of documentation issue is this?
      description: Choose as many as apply.
      options:
        - Typo
        - Incorrect information
        - Unclear information
        - Improved explanation
        - Removed confusion
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-docs
    attributes:
      label: How do you think the documentation should be improved?
      description: Tell us about your idea.
      placeholder: It would be nice if...
    validations:
      required: true
